version: 2

updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'increase'
    groups:
      npm-production-dependencies:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      npm-development-dependencies:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
