# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Scorecard security analysis"

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "25 10 * * 3"
  workflow_dispatch:

permissions: {}

jobs:
  analyze:
    name: "Scorecard security analysis"
    runs-on: "ubuntu-latest"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - name: "Perform security analysis"
        uses: "ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46"
        with:
          results_file: "./results.sarif"
          results_format: "sarif"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_results: false
      - name: "Upload SARIF file"
        uses: "github/codeql-action/upload-sarif@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169"
        with:
          sarif_file: "./results.sarif"
